### ISSUE TITLE
feature: additional s3 configuration flags

### ISSUE THREAD

**Issue by egallis31** [siderolabs/talos-backup#19]
The default aws-go-sdk-v2 configuration for the S3 client appears to be using the `addressing_style` of auto, as is default. To upload to Minio, in most cases path style is utilized.

Based on how the package operates it appears that the only way to change the `addessing_style` is via the object itself, no environment variables available officially, and does not seem to respect aws config file for configuration flags.

potential update for s3.go  - https://stackoverflow.com/a/66141318

Requesting this additional feature addition for usage with Minio for S3 backup.

**Comment by frezbo** [comment]
not sure what's missing, this already works with minio and as we use minio in integration tests

**Comment by cgrard** [comment]
I had a problem and this issue put me on the right track.

Since the v0.1.0-beta.1 release we can't send snapshots to our minio cluster, the URL it builds and tries to resolve does not exist because it is bucket.s3endpoint.tld

So out of curiosity I downgraded to v0.1.0-beta.0 and it works, so it seems to me that there's indeed something fishy about how the URL is built in the latest version.

**Comment by NikolaiBessonov** [comment]
I have the same problem. Any workarounds ?

**Comment by cgrard** [comment]
I have a PR submitted and waiting for approval for this : https://github.com/siderolabs/talos-backup/pull/20

**Comment by frezbo** [comment]
https://github.com/siderolabs/talos-backup/releases/tag/v0.1.0-beta.2 should have a fix
